In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical

# CIFAR10 데이터셋 로드
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# 데이터 전처리
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# 모델 생성
model = models.Sequential([
    layers.Flatten(input_shape=(32, 32, 3)),
    layers.Dense(512, activation='relu'),
    layers.Dense(256, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# 모델 컴파일
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 모델 훈련
history = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))

# 모델 평가
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)


170498071/170498071 [==============================] - 2s 0us/step
Epoch 1/10
1563/1563 [==============================] - 46s 27ms/step - loss: 1.8462 - accuracy: 0.3334 - val_loss: 1.7531 - val_accuracy: 0.3696
Epoch 2/10
1563/1563 [==============================] - 36s 23ms/step - loss: 1.6558 - accuracy: 0.4089 - val_loss: 1.6241 - val_accuracy: 0.4076
Epoch 3/10
1563/1563 [==============================] - 37s 24ms/step - loss: 1.5856 - accuracy: 0.4320 - val_loss: 1.5536 - val_accuracy: 0.4468
Epoch 4/10
1563/1563 [==============================] - 38s 24ms/step - loss: 1.5359 - accuracy: 0.4503 - val_loss: 1.5067 - val_accuracy: 0.4580
Epoch 5/10
1563/1563 [==============================] - 37s 23ms/step - loss: 1.5010 - accuracy: 0.4626 - val_loss: 1.5402 - val_accuracy: 0.4506
Epoch 6/10
1563/1563 [==============================] - 37s 23ms/step - loss: 1.4751 - accuracy: 0.4737 - val_loss: 1.5129 - val_accuracy: 0.4550
Epoch 7/10
1563/1563 [==============================] - 3

In [2]:
# Dropout 층 추가
model_with_dropout = models.Sequential([
    layers.Flatten(input_shape=(32, 32, 3)),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.2),  # Dropout 추가
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.2),  # Dropout 추가
    layers.Dense(10, activation='softmax')
])

# 모델 컴파일
model_with_dropout.compile(optimizer='adam',
                            loss='categorical_crossentropy',
                            metrics=['accuracy'])

# 모델 훈련
history = model_with_dropout.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))

# 모델 평가
test_loss, test_acc = model_with_dropout.evaluate(x_test, y_test)
print('Test accuracy with Dropout:', test_acc)

Epoch 1/10
1563/1563 [==============================] - 40s 25ms/step - loss: 1.9841 - accuracy: 0.2685 - val_loss: 1.8295 - val_accuracy: 0.3424
Epoch 2/10
1563/1563 [==============================] - 38s 24ms/step - loss: 1.8675 - accuracy: 0.3163 - val_loss: 1.7480 - val_accuracy: 0.3682
Epoch 3/10
1563/1563 [==============================] - 38s 24ms/step - loss: 1.8196 - accuracy: 0.3330 - val_loss: 1.7122 - val_accuracy: 0.3852
Epoch 4/10
1563/1563 [==============================] - 41s 26ms/step - loss: 1.7917 - accuracy: 0.3442 - val_loss: 1.7866 - val_accuracy: 0.3552
Epoch 5/10
1563/1563 [==============================] - 38s 24ms/step - loss: 1.7729 - accuracy: 0.3528 - val_loss: 1.7047 - val_accuracy: 0.3835
Epoch 6/10
1563/1563 [==============================] - 39s 25ms/step - loss: 1.7525 - accuracy: 0.3622 - val_loss: 1.6827 - val_accuracy: 0.4002
Epoch 7/10
1563/1563 [==============================] - 37s 24ms/step - loss: 1.7383 - accuracy: 0.3687 - val_loss: 1.6624 -

In [3]:
# 모델 생성 - Dropout 층 없는 경우
model_no_dropout = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(32, 32, 3)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

# 모델 컴파일
model_no_dropout.compile(optimizer='adam',
                          loss='categorical_crossentropy',
                          metrics=['accuracy'])

# 모델 훈련
history_no_dropout = model_no_dropout.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))

# 모델 평가 - Dropout 층 없는 경우
test_loss_no_dropout, test_acc_no_dropout = model_no_dropout.evaluate(x_test, y_test)
print('Test accuracy without Dropout:', test_acc_no_dropout)

# Dropout 층 추가
model_with_dropout = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(32, 32, 3)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),  # Dropout 추가
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.2),  # Dropout 추가
    tf.keras.layers.Dense(10, activation='softmax')
])

# 모델 컴파일
model_with_dropout.compile(optimizer='adam',
                            loss='categorical_crossentropy',
                            metrics=['accuracy'])

# 모델 훈련
history_with_dropout = model_with_dropout.fit(x_train, y_train, epochs=10, batch_size=32, validation_data=(x_test, y_test))

# 모델 평가 - Dropout 층 있는 경우
test_loss_with_dropout, test_acc_with_dropout = model_with_dropout.evaluate(x_test, y_test)
print('Test accuracy with Dropout:', test_acc_with_dropout)

# 과대적합 비교
print('Overfitting comparison:')
print('Test accuracy without Dropout:', test_acc_no_dropout)
print('Test accuracy with Dropout:', test_acc_with_dropout)

Epoch 1/10
1563/1563 [==============================] - 39s 24ms/step - loss: 1.8549 - accuracy: 0.3317 - val_loss: 1.7335 - val_accuracy: 0.3756
Epoch 2/10
1563/1563 [==============================] - 37s 24ms/step - loss: 1.6706 - accuracy: 0.4007 - val_loss: 1.6605 - val_accuracy: 0.4118
Epoch 3/10
1563/1563 [==============================] - 38s 24ms/step - loss: 1.5920 - accuracy: 0.4312 - val_loss: 1.5410 - val_accuracy: 0.4523
Epoch 4/10
1563/1563 [==============================] - 38s 25ms/step - loss: 1.5392 - accuracy: 0.4502 - val_loss: 1.5279 - val_accuracy: 0.4591
Epoch 5/10
1563/1563 [==============================] - 38s 24ms/step - loss: 1.4983 - accuracy: 0.4642 - val_loss: 1.4976 - val_accuracy: 0.4622
Epoch 6/10
1563/1563 [==============================] - 38s 25ms/step - loss: 1.4722 - accuracy: 0.4740 - val_loss: 1.4932 - val_accuracy: 0.4716
Epoch 7/10
1563/1563 [==============================] - 38s 24ms/step - loss: 1.4441 - accuracy: 0.4835 - val_loss: 1.5160 -

In [4]:
import numpy as np
from sklearn.metrics import confusion_matrix

# 몬테카를로 시뮬레이션 횟수 설정
num_monte_carlo = 50

# 각 클래스별 몬테카를로 예측을 저장할 리스트 초기화
monte_carlo_predictions = [[] for _ in range(len(y_test))]

# 몬테카를로 시뮬레이션 실행
for _ in range(num_monte_carlo):
    predictions = model_with_dropout.predict(x_test)  # 드롭아웃 적용 모델로 예측
    for i, pred in enumerate(predictions):
        monte_carlo_predictions[i].append(np.argmax(pred))  # 가장 높은 확률을 갖는 클래스를 저장

# 각 데이터 포인트에 대한 몬테카를로 예측의 평균을 계산
monte_carlo_averaged_predictions = [np.argmax(np.bincount(preds)) for preds in monte_carlo_predictions]

# 혼동 행렬 계산
conf_matrix = confusion_matrix(np.argmax(y_test, axis=1), monte_carlo_averaged_predictions)

print("Confusion Matrix:")
print(conf_matrix)

313/313 [==============================] - 2s 6ms/step
Confusion Matrix:
[[460  41  39  62  19   6  45  28 177 123]
 [ 35 450   2  46   9  11  33  23 100 291]
 [109  27 159 135 162  57 219  58  31  43]
 [ 32  14  51 331  40 132 238  42  33  87]
 [ 58   9  90 111 331  33 232  65  28  43]
 [ 17  12  52 254  70 278 184  47  38  48]
 [  8  11  30 117 113  28 624  19   8  42]
 [ 27  23  42  93 105  64 121 378  18 129]
 [119  56   5  62   5   9  17  13 553 161]
 [ 22 123   1  53   3  10  37  32  91 628]]


주로 대각선에 있는 값들이 높고 비대각선 값들이 낮을 수록 모델의 성능이 좋다. 위의 행렬은 대각선 요소가 높고, 주요 오분류 패턴이 나타나지 않으므로 괜찮은 성능을 가지고 있다.

Adam 기법을 사용했습니다.

In [5]:
# 모델 생성
model = models.Sequential([
    layers.Flatten(input_shape=(32, 32, 3)),
    layers.Dense(512, activation='relu'),
    layers.Dense(256, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# 모델 컴파일
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)  # Adam 옵티마이저, 학습률을 0.001로 설정
model.compile(optimizer=optimizer,
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 모델 훈련
history = model.fit(x_train, y_train, epochs=15, batch_size=64, validation_data=(x_test, y_test))  # 에포크를 15로 변경, 배치 크기를 64로 변경

# 모델 평가
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)


Epoch 1/15
782/782 [==============================] - 25s 31ms/step - loss: 1.8746 - accuracy: 0.3274 - val_loss: 1.7268 - val_accuracy: 0.3828
Epoch 2/15
782/782 [==============================] - 23s 29ms/step - loss: 1.6716 - accuracy: 0.3985 - val_loss: 1.6120 - val_accuracy: 0.4212
Epoch 3/15
782/782 [==============================] - 23s 30ms/step - loss: 1.5820 - accuracy: 0.4361 - val_loss: 1.5507 - val_accuracy: 0.4493
Epoch 4/15
782/782 [==============================] - 22s 28ms/step - loss: 1.5292 - accuracy: 0.4515 - val_loss: 1.5398 - val_accuracy: 0.4598
Epoch 5/15
782/782 [==============================] - 23s 29ms/step - loss: 1.4881 - accuracy: 0.4724 - val_loss: 1.5134 - val_accuracy: 0.4636
Epoch 6/15
782/782 [==============================] - 23s 29ms/step - loss: 1.4524 - accuracy: 0.4812 - val_loss: 1.4694 - val_accuracy: 0.4743
Epoch 7/15
782/782 [==============================] - 22s 29ms/step - loss: 1.4217 - accuracy: 0.4910 - val_loss: 1.4651 - val_accuracy:

기존 다층 퍼셉트론의 정확도 : Test accuracy: 0.47530001401901245

Adam 기법으로 변형했을 때의 정확도 : Test accuracy: 0.5080000162124634